CREATE DATABASE IF NOT EXISTS partner_db;
USE partner_db;

CREATE TABLE IF NOT EXISTS partners (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  imageUrl VARCHAR(1000) NOT NULL,
  websiteUrl VARCHAR(1000),
  description TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  isActive BOOLEAN DEFAULT TRUE,
  `order` INT DEFAULT 0
); 